// Package market reads the Herdr plugin marketplace index and the manifests it
// points at.
//
// The index at IndexURL lists public GitHub repositories tagged with the
// herdr-plugin topic, one entry per repository, each with the manifests found
// on its default branch. It is generated by herdr.dev and is not a reviewed
// catalog.
package market

import (
	"cmp"
	"slices"
	"strings"
	"time"

	"github.com/vika2603/herdr-plugin-manager/internal/source"
)

// IndexURL is where herdr.dev publishes the marketplace index.
const IndexURL = "https://assets.herdr.dev/plugins/index.json"

// SchemaVersion is the index format this package decodes.
const SchemaVersion = 1

// Index is the marketplace index document.
type Index struct {
	SchemaVersion int          `json:"schemaVersion"`
	GeneratedAt   time.Time    `json:"generatedAt"`
	Repositories  []Repository `json:"plugins"`
}

// Repository is one GitHub repository in the index.
type Repository struct {
	FullName    string    `json:"fullName"`
	Owner       string    `json:"owner"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	URL         string    `json:"url"`
	Stars       int       `json:"stars"`
	Language    string    `json:"language"`
	Topics      []string  `json:"topics"`
	CreatedAt   time.Time `json:"createdAt"`
	PushedAt    time.Time `json:"pushedAt"`
	// FirstSeenAt is when herdr.dev first indexed the repository.
	FirstSeenAt time.Time `json:"firstSeenAt"`
	// StarsDelta7d is the star gain over the last seven days.
	StarsDelta7d int        `json:"starsDelta7d"`
	HeadCommit   string     `json:"headCommit"`
	Manifests    []Manifest `json:"manifests"`
}

// Manifest is the metadata the index keeps for one herdr-plugin.toml.
type Manifest struct {
	Path            string   `json:"path"`
	ID              string   `json:"id"`
	Name            string   `json:"name"`
	Version         string   `json:"version"`
	MinHerdrVersion string   `json:"minHerdrVersion"`
	Description     string   `json:"description"`
	Platforms       []string `json:"platforms"`
}

// Entry is one installable plugin: a manifest together with its repository.
type Entry struct {
	Repo     *Repository
	Manifest Manifest
	Source   source.GitHub
}

// Description prefers the manifest's own description over the repository's.
func (e Entry) Description() string {
	if e.Manifest.Description != "" {
		return e.Manifest.Description
	}
	return e.Repo.Description
}

// Entries flattens the index into one entry per manifest.
func (ix *Index) Entries() []Entry {
	var out []Entry
	for i := range ix.Repositories {
		repo := &ix.Repositories[i]
		for _, m := range repo.Manifests {
			out = append(out, Entry{Repo: repo, Manifest: m, Source: source.FromManifestPath(repo.Owner, repo.Name, m.Path)})
		}
	}
	return out
}

// Find returns the entry whose plugin id or source shorthand is key.
func Find(entries []Entry, key string) (Entry, bool) {
	for _, e := range entries {
		if e.Manifest.ID == key || strings.EqualFold(e.Source.String(), key) {
			return e, true
		}
	}
	return Entry{}, false
}

// Order is how entries are sorted.
type Order int

// Orders offered for browsing: relevance to the search terms, then the
// orders of the marketplace website, which they follow.
const (
	ByRelevance Order = iota
	ByPopular
	ByTrending
	ByRecent
	ByNewest
	ByName
)

var orderNames = []string{"relevance", "popular", "trending", "recent", "newest", "name"}

// trendingMinGain is the weekly star gain the marketplace website requires
// before it ranks a repository by growth rate.
const trendingMinGain = 10

func (o Order) String() string { return orderNames[o] }

// Next cycles through the orders.
func (o Order) Next() Order { return (o + 1) % Order(len(orderNames)) }

// ParseOrder reads an order name.
func ParseOrder(name string) (Order, bool) {
	i := slices.Index(orderNames, name)
	return Order(max(i, 0)), i >= 0
}

// Sort orders entries in place. Ties fall back to the plugin id so the order
// is stable across refreshes. Relevance needs search terms, so without them
// it sorts by popularity; Search ranks by relevance.
func Sort(entries []Entry, by Order) {
	slices.SortStableFunc(entries, func(a, b Entry) int { return compareBy(a, b, by) })
}

func compareBy(a, b Entry, by Order) int {
	var c int
	switch by {
	case ByRelevance, ByPopular:
		c = cmp.Or(cmp.Compare(b.Repo.Stars, a.Repo.Stars), b.Repo.PushedAt.Compare(a.Repo.PushedAt))
	case ByTrending:
		c = cmp.Or(cmp.Compare(trendingScore(b.Repo), trendingScore(a.Repo)),
			cmp.Compare(b.Repo.StarsDelta7d, a.Repo.StarsDelta7d), cmp.Compare(b.Repo.Stars, a.Repo.Stars))
	case ByRecent:
		c = b.Repo.PushedAt.Compare(a.Repo.PushedAt)
	case ByNewest:
		c = listedAt(b.Repo).Compare(listedAt(a.Repo))
	case ByName:
		c = strings.Compare(strings.ToLower(a.Manifest.Name), strings.ToLower(b.Manifest.Name))
	}
	if c != 0 {
		return c
	}
	return strings.Compare(a.Manifest.ID, b.Manifest.ID)
}

// trendingScore is the weekly star gain relative to the stars before it, or
// -1 below the minimum gain.
func trendingScore(r *Repository) float64 {
	if r.StarsDelta7d < trendingMinGain {
		return -1
	}
	return float64(r.StarsDelta7d) / float64(max(r.Stars-r.StarsDelta7d, 1))
}

// listedAt is when the repository joined the marketplace; older indexes
// lack that, and its creation on GitHub stands in.
func listedAt(r *Repository) time.Time {
	if r.FirstSeenAt.IsZero() {
		return r.CreatedAt
	}
	return r.FirstSeenAt
}
